package com.github.casiopicture;

import com.github.casiopicture.engine.data.ConversionOptions;
import com.github.casiopicture.engine.data.ConversionResult;
import com.github.casiopicture.engine.data.Format;
import com.github.casiopicture.engine.encoder.FileEncoder;
import org.junit.jupiter.api.AfterAll;
import org.junit.jupiter.api.DynamicTest;
import org.junit.jupiter.api.TestFactory;

import java.awt.image.BufferedImage;
import java.io.IOException;
import java.io.InputStream;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;
import java.util.stream.Collectors;
import java.util.zip.GZIPInputStream;

import static org.junit.jupiter.api.Assertions.fail;

/**
 * Checks every Java encoder against bytes produced by the original img2calc code.
 *
 * <p>The vectors in {@code src/test/resources/ref} are generated by {@code tools/refgen/refgen.mjs},
 * which runs the encoder functions transcribed verbatim from {@code tmp/index.html}. Each vector
 * pairs an exact RGBA input with the exact output bytes the reference produced for it, so any
 * difference here is a defect in the port.
 *
 * <p>This matters more than it might look: the Casio and TI containers carry nested size fields and
 * checksums, and a calculator refuses to open a file whose header arithmetic is off by one byte.
 *
 * <p>Regenerate with {@code ./casiopicture.sh refgen} after touching the reference.
 */
public class ReferenceVectorTest {

    private static final Path REF = Path.of("src/test/resources/ref");

    private record Vector(
        String format, String target, String pattern,
        int width, int height, String palette,
        Path image, Path vector,
        String oncalcName, int oncalcNum, String calcName
    ) {
        String id() {
            return format + " " + pattern + " " + width + "x" + height;
        }
    }

    private static List<Vector> loadManifest() throws IOException {
        List<String> lines = Files.readAllLines(REF.resolve("manifest.tsv"), StandardCharsets.UTF_8);
        List<Vector> out = new ArrayList<>();
        for (String line : lines.subList(1, lines.size())) {   // row 0 is the header
            if (line.isBlank()) continue;
            String[] f = line.split("\t", -1);
            out.add(new Vector(f[0], f[1], f[2],
                Integer.parseInt(f[3]), Integer.parseInt(f[4]),
                "-".equals(f[5]) ? null : f[5],
                REF.resolve(f[6]), REF.resolve(f[7]),
                f[8], Integer.parseInt(f[9]), f[10]));
        }
        return out;
    }

    /**
     * Loads a gzipped raw RGBA buffer as a non-premultiplied ARGB image.
     *
     * <p>Raw RGBA rather than PNG so there is no decoder between the fixture and the encoder: the
     * pixels the reference saw are the pixels the Java encoder gets, alpha included.
     */
    private static BufferedImage loadImage(Path path, int width, int height) throws IOException {
        byte[] rgba;
        try (InputStream in = new GZIPInputStream(Files.newInputStream(path))) {
            rgba = in.readAllBytes();
        }
        BufferedImage image = new BufferedImage(width, height, BufferedImage.TYPE_INT_ARGB);
        for (int i = 0; i < width * height; i++) {
            int r = rgba[i * 4] & 0xFF;
            int g = rgba[i * 4 + 1] & 0xFF;
            int b = rgba[i * 4 + 2] & 0xFF;
            int a = rgba[i * 4 + 3] & 0xFF;
            image.setRGB(i % width, i / width, (a << 24) | (r << 16) | (g << 8) | b);
        }
        return image;
    }

    /** Per-format tallies, so the run ends with a readable scoreboard instead of 591 stack traces. */
    private static final Map<String, int[]> TALLY = new TreeMap<>();

    @TestFactory
    Iterable<DynamicTest> matchesReference() throws IOException {
        List<Vector> vectors = loadManifest();
        // One dynamic test per vector, so a failure names the exact format/pattern/size rather than
        // stopping the whole suite at the first mismatch.
        return vectors.stream()
            .map(v -> DynamicTest.dynamicTest(v.id(), () -> {
                int[] t = TALLY.computeIfAbsent(v.format(), k -> new int[2]);
                t[1]++;
                check(v);
                t[0]++;
            }))
            .collect(Collectors.toList());
    }

    @AfterAll
    static void report() {
        if (TALLY.isEmpty()) return;
        int ok = TALLY.values().stream().mapToInt(t -> t[0]).sum();
        int total = TALLY.values().stream().mapToInt(t -> t[1]).sum();

        // Sort worst-first: the formats needing work float to the top.
        Map<String, int[]> sorted = new LinkedHashMap<>();
        TALLY.entrySet().stream()
            .sorted((a, b) -> Double.compare(
                (double) a.getValue()[0] / a.getValue()[1],
                (double) b.getValue()[0] / b.getValue()[1]))
            .forEach(e -> sorted.put(e.getKey(), e.getValue()));

        StringBuilder sb = new StringBuilder("\nreference vectors vs img2calc\n");
        sorted.forEach((format, t) -> sb.append(String.format("  %-4s %-18s %d/%d%n",
            t[0] == t[1] ? "ok" : "FAIL", format, t[0], t[1])));
        sb.append(String.format("%n  %d/%d vectors match%n", ok, total));
        System.out.println(sb);

        try {
            Files.createDirectories(Path.of("target"));
            Files.writeString(Path.of("target/reference-vectors.txt"), sb.toString());
        } catch (IOException ignored) {
            // The console output above is the real deliverable; the file is a convenience.
        }
    }

    private static void check(Vector v) throws Exception {
        byte[] expected = Files.readAllBytes(v.vector());
        BufferedImage image = loadImage(v.image(), v.width(), v.height());

        Format format = Format.fromString(v.format());
        ConversionOptions options = new ConversionOptions(
            v.width(), v.height(), 0, true, false);

        ConversionResult result = FileEncoder.getEncoder(format)
            .encode(image, format, v.oncalcName() + ".png", options);
        byte[] actual = result.fileBytes();

        if (!java.util.Arrays.equals(expected, actual)) {
            // Surefire reports dynamic tests under the factory method name, so the vector id has to
            // travel in the message or a failure is untraceable.
            fail(v.id() + " [" + v.vector().getFileName() + "]\n" + diff(expected, actual));
        }
    }

    /** Renders the first divergence as side-by-side hex, which is what you actually need to debug. */
    private static String diff(byte[] expected, byte[] actual) {
        int at = -1;
        for (int i = 0; i < Math.min(expected.length, actual.length); i++) {
            if (expected[i] != actual[i]) { at = i; break; }
        }
        StringBuilder sb = new StringBuilder();
        if (expected.length != actual.length) {
            sb.append(String.format("length: expected %d, got %d%n", expected.length, actual.length));
        }
        if (at < 0) {
            if (expected.length == actual.length) return "arrays differ but no differing byte found";
            at = Math.min(expected.length, actual.length);
        } else {
            sb.append(String.format("first difference at 0x%X (%d): expected 0x%02X, got 0x%02X%n",
                at, at, expected[at] & 0xFF, actual[at] & 0xFF));
        }

        int from = Math.max(0, (at - 16) & ~0xF);
        int to = Math.min(Math.max(expected.length, actual.length), from + 64);
        sb.append("        expected                          actual\n");
        for (int row = from; row < to; row += 16) {
            sb.append(String.format("%06X  %-34s%-34s%n", row, hex(expected, row), hex(actual, row)));
        }
        return sb.toString();
    }

    private static String hex(byte[] data, int from) {
        StringBuilder sb = new StringBuilder();
        for (int i = from; i < from + 16; i++) {
            sb.append(i < data.length ? String.format("%02X ", data[i] & 0xFF) : "   ");
        }
        return sb.toString();
    }

    /** Sanity check: the fixtures must actually be present, or every other test is vacuously green. */
    @TestFactory
    Iterable<DynamicTest> manifestIsPopulated() throws IOException {
        List<Vector> vectors = loadManifest();
        Map<String, Long> byFormat = vectors.stream()
            .collect(Collectors.groupingBy(Vector::format, Collectors.counting()));
        return List.of(DynamicTest.dynamicTest(
            "manifest lists " + vectors.size() + " vectors across " + byFormat.size() + " formats",
            () -> {
                if (vectors.size() < 100) {
                    fail("manifest looks truncated (" + vectors.size()
                        + " vectors); run ./casiopicture.sh refgen");
                }
            }));
    }
}
